# == Schema Information
# Schema version: 20160202150722
#
# Table name: residents
#
#  id         :integer          not null, primary key
#  name       :string           not null
#  multiplier :integer          default(2), not null
#  unit_id    :integer
#  bill_costs :integer          default(0), not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
# Indexes
#
#  index_residents_on_name     (name) UNIQUE
#  index_residents_on_unit_id  (unit_id)
#
# Foreign Keys
#
#  fk_rails_8ddf6a82d6  (unit_id => units.id)
#

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe ResidentsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Resident. As you add validations to Resident, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ResidentsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all residents as @residents" do
      resident = Resident.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:residents)).to eq([resident])
    end
  end

  describe "GET #show" do
    it "assigns the requested resident as @resident" do
      resident = Resident.create! valid_attributes
      get :show, {:id => resident.to_param}, valid_session
      expect(assigns(:resident)).to eq(resident)
    end
  end

  describe "GET #new" do
    it "assigns a new resident as @resident" do
      get :new, {}, valid_session
      expect(assigns(:resident)).to be_a_new(Resident)
    end
  end

  describe "GET #edit" do
    it "assigns the requested resident as @resident" do
      resident = Resident.create! valid_attributes
      get :edit, {:id => resident.to_param}, valid_session
      expect(assigns(:resident)).to eq(resident)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Resident" do
        expect {
          post :create, {:resident => valid_attributes}, valid_session
        }.to change(Resident, :count).by(1)
      end

      it "assigns a newly created resident as @resident" do
        post :create, {:resident => valid_attributes}, valid_session
        expect(assigns(:resident)).to be_a(Resident)
        expect(assigns(:resident)).to be_persisted
      end

      it "redirects to the created resident" do
        post :create, {:resident => valid_attributes}, valid_session
        expect(response).to redirect_to(Resident.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved resident as @resident" do
        post :create, {:resident => invalid_attributes}, valid_session
        expect(assigns(:resident)).to be_a_new(Resident)
      end

      it "re-renders the 'new' template" do
        post :create, {:resident => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested resident" do
        resident = Resident.create! valid_attributes
        put :update, {:id => resident.to_param, :resident => new_attributes}, valid_session
        resident.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested resident as @resident" do
        resident = Resident.create! valid_attributes
        put :update, {:id => resident.to_param, :resident => valid_attributes}, valid_session
        expect(assigns(:resident)).to eq(resident)
      end

      it "redirects to the resident" do
        resident = Resident.create! valid_attributes
        put :update, {:id => resident.to_param, :resident => valid_attributes}, valid_session
        expect(response).to redirect_to(resident)
      end
    end

    context "with invalid params" do
      it "assigns the resident as @resident" do
        resident = Resident.create! valid_attributes
        put :update, {:id => resident.to_param, :resident => invalid_attributes}, valid_session
        expect(assigns(:resident)).to eq(resident)
      end

      it "re-renders the 'edit' template" do
        resident = Resident.create! valid_attributes
        put :update, {:id => resident.to_param, :resident => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested resident" do
      resident = Resident.create! valid_attributes
      expect {
        delete :destroy, {:id => resident.to_param}, valid_session
      }.to change(Resident, :count).by(-1)
    end

    it "redirects to the residents list" do
      resident = Resident.create! valid_attributes
      delete :destroy, {:id => resident.to_param}, valid_session
      expect(response).to redirect_to(residents_url)
    end
  end

end
